### ISSUE TITLE
Could you tell me how to process the PEMS-BAY dataset?Thanks

### ISSUE THREAD

**Issue by Azusa-Yuan** [tsy935/graphs4mer#1]
I download PEMS-BAY.h5 form your link.I find your code need train.npz, test.npz and val.npz, so i use the script from DCRNN to create them.Then, the program runs out of 32G memory. So did i do something wrong?

**Comment by tsy935** [comment]
To clarify - did you get the error when you were processing the data from DCRNN repo or did you get it when you were running the model training script?

**Comment by Azusa-Yuan** [comment]
> To clarify - did you get the error when you were processing the data from DCRNN repo or did you get it when you were running the model training script?
yeah, i get the train.npz, test.npz and val.npz.I've solved this problem, now. I find when you create datasets,  you add the same Adj matrix in every input x. I delete it and save many memory and the code work well.

**Comment by tsy935** [comment]
Great! I'll close this now.
