### ISSUE TITLE
The result in PEMS-BAY could be wrong 

### ISSUE THREAD

**Issue by Azusa-Yuan** [tsy935/graphs4mer#2]
You code calculate the mean MAE on the test datasets and I get the result mean MAE 1.69.But in your paper,  you compare  the result with other baselines horizen 12 MAE results . It is not fair.

**Comment by tsy935** [comment]
Thanks for catching this. We have fixed it in the training script. Please see https://github.com/tsy935/graphs4mer/blob/traffic/train.py#L446-L453
