### ISSUE TITLE
RuntimeError when training graphs4mer on TUH

### ISSUE THREAD

**Issue by dykestra** [tsy935/graphs4mer#6]
I've been getting the following error when attempting to train on TUH (running run_tuh.sh):

> `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [588]] is at version 2; expected version 0 instead.`

All code related to models is unchanged so I'm not sure what could be causing this.
This is with pytorch=1.12.0 and pytorch-lightning=1.9.5

**Comment by JosefSlavicek** [comment]
I was facing the same issue, resolved it by downgrading to torch_geometric==2.3.0

**Comment by dykestra** [comment]
awesome, downgrading torch_geometric worked. thanks!

**Comment by dykestra** [comment]
awesome, downgrading torch_geometric worked. thanks!

**Comment by ramzan-basheer** [comment]
thanks a lot. It worked.
